var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,h,l){a instanceof String&&(a=String(a));for(var q=a.length,m=0;m<q;m++){var b=a[m];if(h.call(l,b,m,a))return{i:m,v:b}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,h,l){if(a==Array.prototype||a==Object.prototype)return a;a[h]=l.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var h=0;h<a.length;++h){var l=a[h];if(l&&l.Math==Math)return l}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,h){var l=$jscomp.propertyToPolyfillSymbol[h];if(null==l)return a[h];l=a[l];return void 0!==l?l:a[h]};
$jscomp.polyfill=function(a,h,l,q){h&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,h,l,q):$jscomp.polyfillUnisolated(a,h,l,q))};$jscomp.polyfillUnisolated=function(a,h,l,q){l=$jscomp.global;a=a.split(".");for(q=0;q<a.length-1;q++){var m=a[q];if(!(m in l))return;l=l[m]}a=a[a.length-1];q=l[a];h=h(q);h!=q&&null!=h&&$jscomp.defineProperty(l,a,{configurable:!0,writable:!0,value:h})};
$jscomp.polyfillIsolated=function(a,h,l,q){var m=a.split(".");a=1===m.length;q=m[0];q=!a&&q in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var b=0;b<m.length-1;b++){var g=m[b];if(!(g in q))return;q=q[g]}m=m[m.length-1];l=$jscomp.IS_SYMBOL_NATIVE&&"es6"===l?q[m]:null;h=h(l);null!=h&&(a?$jscomp.defineProperty($jscomp.polyfills,m,{configurable:!0,writable:!0,value:h}):h!==l&&($jscomp.propertyToPolyfillSymbol[m]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(m):$jscomp.POLYFILL_PREFIX+m,m=
$jscomp.propertyToPolyfillSymbol[m],$jscomp.defineProperty(q,m,{configurable:!0,writable:!0,value:h})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(h,l){return $jscomp.findInternal(this,h,l).v}},"es6","es3");
define(["jquery"],function(a){var h=function(b,g,k){var d={invalid:[],getCaret:function(){try{var c=0,f=b.get(0),e=document.selection,t=f.selectionStart;if(e&&-1===navigator.appVersion.indexOf("MSIE 10")){var n=e.createRange();n.moveStart("character",-d.val().length);c=n.text.length}else if(t||"0"===t)c=t;return c}catch(u){}},setCaret:function(c){try{if(b.is(":focus")){var f=b.get(0);if(f.setSelectionRange)f.setSelectionRange(c,c);else{var e=f.createTextRange();e.collapse(!0);e.moveEnd("character",
c);e.moveStart("character",c);e.select()}}}catch(t){}},events:function(){b.on("keydown.mask",function(c){b.data("mask-keycode",c.keyCode||c.which);b.data("mask-previus-value",b.val());b.data("mask-previus-caret-pos",d.getCaret());d.maskDigitPosMapOld=d.maskDigitPosMap}).on(a.jMaskGlobals.useInput?"input.mask":"keyup.mask",d.behaviour).on("paste.mask drop.mask",function(){setTimeout(function(){b.keydown().keyup()},100)}).on("change.mask",function(){b.data("changed",!0)}).on("blur.mask",function(){x===
d.val()||b.data("changed")||b.trigger("change");b.data("changed",!1)}).on("blur.mask",function(){x=d.val()}).on("focus.mask",function(c){!0===k.selectOnFocus&&a(c.target).select()}).on("focusout.mask",function(){k.clearIfNotMatch&&!G.test(d.val())&&d.val("")})},getRegexMask:function(){for(var c=[],f,e,t,n,u=0;u<g.length;u++)(f=r.translation[g.charAt(u)])?(e=f.pattern.toString().replace(/.{1}$|^.{1}/g,""),t=f.optional,(f=f.recursive)?(c.push(g.charAt(u)),n={digit:g.charAt(u),pattern:e}):c.push(t||
f?e+"?":e)):c.push(g.charAt(u).replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&"));c=c.join("");n&&(c=c.replace(new RegExp("("+n.digit+"(.*"+n.digit+")?)"),"($1)?").replace(new RegExp(n.digit,"g"),n.pattern));return new RegExp(c)},destroyEvents:function(){b.off("input keydown keyup paste drop blur focusout ".split(" ").join(".mask "))},val:function(c){var f=b.is("input")?"val":"text";if(0<arguments.length){if(b[f]()!==c)b[f](c);f=b}else f=b[f]();return f},calculateCaretPosition:function(c){var f=d.getMasked(),
e=d.getCaret();if(c!==f){var t=b.data("mask-previus-caret-pos")||0;f=f.length;var n=c.length,u=c=0,v=0,w=0,p;for(p=e;p<f&&d.maskDigitPosMap[p];p++)u++;for(p=e-1;0<=p&&d.maskDigitPosMap[p];p--)c++;for(p=e-1;0<=p;p--)d.maskDigitPosMap[p]&&v++;for(p=t-1;0<=p;p--)d.maskDigitPosMapOld[p]&&w++;e>n?e=10*f:t>=e&&t!==n?d.maskDigitPosMapOld[e]||(t=e,e=e-(w-v)-c,d.maskDigitPosMap[e]&&(e=t)):e>t&&(e=e+(v-w)+u)}return e},behaviour:function(c){c=c||window.event;d.invalid=[];var f=b.data("mask-keycode");if(-1===
a.inArray(f,r.byPassKeys)){f=d.getMasked();var e=d.getCaret(),t=b.data("mask-previus-value")||"";setTimeout(function(){d.setCaret(d.calculateCaretPosition(t))},a.jMaskGlobals.keyStrokeCompensation);d.val(f);d.setCaret(e);return d.callbacks(c)}},getMasked:function(c,f){var e=[],t=void 0===f?d.val():f+"",n=0,u=g.length,v=0,w=t.length,p=1,B="push",z=-1,E=0;f=[];if(k.reverse){B="unshift";p=-1;var C=0;n=u-1;v=w-1;var H=function(){return-1<n&&-1<v}}else C=u-1,H=function(){return n<u&&v<w};for(var F;H();){var D=
g.charAt(n),A=t.charAt(v),y=r.translation[D];if(y)A.match(y.pattern)?(e[B](A),y.recursive&&(-1===z?z=n:n===C&&n!==z&&(n=z-p),C===z&&(n-=p)),n+=p):A===F?(E--,F=void 0):y.optional?(n+=p,v-=p):y.fallback?(e[B](y.fallback),n+=p,v-=p):d.invalid.push({p:v,v:A,e:y.pattern}),v+=p;else{if(!c)e[B](D);A===D?(f.push(v),v+=p):(F=D,f.push(v+E),E++);n+=p}}c=g.charAt(C);u!==w+1||r.translation[c]||e.push(c);e=e.join("");d.mapMaskdigitPositions(e,f,w);return e},mapMaskdigitPositions:function(c,f,e){c=k.reverse?c.length-
e:0;d.maskDigitPosMap={};for(e=0;e<f.length;e++)d.maskDigitPosMap[f[e]+c]=1},callbacks:function(c){var f=d.val(),e=f!==x,t=[f,c,b,k],n=function(u,v,w){"function"===typeof k[u]&&v&&k[u].apply(this,w)};n("onChange",!0===e,t);n("onKeyPress",!0===e,t);n("onComplete",f.length===g.length,t);n("onInvalid",0<d.invalid.length,[f,c,b,d.invalid,k])}};b=a(b);var r=this,x=d.val(),G;g="function"===typeof g?g(d.val(),void 0,b,k):g;r.mask=g;r.options=k;r.remove=function(){var c=d.getCaret();r.options.placeholder&&
b.removeAttr("placeholder");b.data("mask-maxlength")&&b.removeAttr("maxlength");d.destroyEvents();d.val(r.getCleanVal());d.setCaret(c);return b};r.getCleanVal=function(){return d.getMasked(!0)};r.getMaskedVal=function(c){return d.getMasked(!1,c)};r.init=function(c){c=c||!1;k=k||{};r.clearIfNotMatch=a.jMaskGlobals.clearIfNotMatch;r.byPassKeys=a.jMaskGlobals.byPassKeys;r.translation=a.extend({},a.jMaskGlobals.translation,k.translation);r=a.extend(!0,{},r,k);G=d.getRegexMask();if(c)d.events(),d.val(d.getMasked());
else{k.placeholder&&b.attr("placeholder",k.placeholder);b.data("mask")&&b.attr("autocomplete","off");c=0;for(var f=!0;c<g.length;c++){var e=r.translation[g.charAt(c)];if(e&&e.recursive){f=!1;break}}f&&b.attr("maxlength",g.length).data("mask-maxlength",!0);d.destroyEvents();d.events();c=d.getCaret();d.val(d.getMasked());d.setCaret(c)}};r.init(!b.is("input"))};a.maskWatchers={};var l=function(){var b=a(this),g={},k=b.attr("data-mask");b.attr("data-mask-reverse")&&(g.reverse=!0);b.attr("data-mask-clearifnotmatch")&&
(g.clearIfNotMatch=!0);"true"===b.attr("data-mask-selectonfocus")&&(g.selectOnFocus=!0);if(q(b,k,g))return b.data("mask",new h(this,k,g))},q=function(b,g,k){k=k||{};var d=a(b).data("mask"),r=JSON.stringify;b=a(b).val()||a(b).text();try{return"function"===typeof g&&(g=g(b)),"object"!==typeof d||r(d.options)!==r(k)||d.mask!==g}catch(x){}},m=function(b){var g=document.createElement("div");b="on"+b;var k=b in g;k||(g.setAttribute(b,"return;"),k="function"===typeof g[b]);return k};a.fn.mask=function(b,
g){g=g||{};var k=this.selector,d=a.jMaskGlobals,r=d.watchInterval;d=g.watchInputs||d.watchInputs;var x=function(){if(q(this,b,g))return a(this).data("mask",new h(this,b,g))};a(this).each(x);k&&""!==k&&d&&(clearInterval(a.maskWatchers[k]),a.maskWatchers[k]=setInterval(function(){a(document).find(k).each(x)},r));return this};a.fn.masked=function(b){return this.data("mask").getMaskedVal(b)};a.fn.unmask=function(){clearInterval(a.maskWatchers[this.selector]);delete a.maskWatchers[this.selector];return this.each(function(){var b=
a(this).data("mask");b&&b.remove().removeData("mask")})};a.fn.cleanVal=function(){return this.data("mask").getCleanVal()};a.applyDataMask=function(b){b=b||a.jMaskGlobals.maskElements;(b instanceof a?b:a(b)).filter(a.jMaskGlobals.dataMaskAttr).each(l)};m={maskElements:"input,td,span,div",dataMaskAttr:"*[data-mask]",dataMask:!0,watchInterval:300,watchInputs:!0,keyStrokeCompensation:10,useInput:!/Chrome\/[2-4][0-9]|SamsungBrowser/.test(window.navigator.userAgent)&&m("input"),watchDataMask:!0,byPassKeys:[9,
16,17,18,36,37,38,39,40,91],translation:{0:{pattern:/\d/},9:{pattern:/\d/,optional:!0},"#":{pattern:/\d/,recursive:!0},A:{pattern:/[a-zA-Z0-9]/},S:{pattern:/[a-zA-Z]/}}};a.jMaskGlobals=a.jMaskGlobals||{};m=a.jMaskGlobals=a.extend(!0,{},m,a.jMaskGlobals);m.dataMask&&a.applyDataMask();setInterval(function(){a.jMaskGlobals.watchDataMask&&a.applyDataMask()},m.watchInterval)});
